import pandas as pd

# missing vector for one person
def missing_data_vector(flagged_df: pd.DataFrame, basis_rate:int=15, missingness_interval:int=15,
                        missing_flag_col:str = 'Missing_Flag', datetime_col:str = 'datetime'):
    """
    Converts missing flagged data into an array of fractional missingness at even spacing for one time series (i.e. one participant).

    Parameters
    ----------
    - flagged_df: pd.DataFrame
        DataFrame with missing flag column (can be generated by preprocess.flag_missing_data)

    - basis_rate: int
        Sampling period in flagged_df, in minutes. Aka 'freq' in preprocess.flag_missing_data

    - missingness_interval: int
        Number of minutes for period in output matrix, allowing for fractional missingness. \
        Should be a whole number multiple of basis_rate.
   
    - missing_flag_col: str 
        Name of column in flagged_df with binary missingness flags. Default from flag_missing_data is 'Missing_Flag'

    - datetime_col : str
        Name of column in flagged_df with timestamps. Default from flag_missing_data is 'datetime'.

    Returns
    -------
    - Series of fractional missingness where each index is a time point.
    """
    # TODO: calculate missing_data_matrix, but on one person
    pass


# missing matrix for population
def missing_data_matrix(flagged_df: pd.DataFrame, basis_rate:int=15, missingness_interval:int=15,
                        missing_flag_col:str = 'Missing_Flag', datetime_col:str = 'datetime', groupby_col:str = 'person_id'):
    """
    Converts missing flagged data into matrix of fractional missingness where each row is one participant
    and each column is one time point. All participants (set by `groupby_col`) will be all be considered
    at the same time points.

    Parameters
    ----------
    - flagged_df: pd.DataFrame
        DataFrame with missing flag column (can be generated by preprocess.flag_missing_data)

    - basis_rate: int
        Sampling period in flagged_df, in minutes. Aka 'freq' in preprocess.flag_missing_data

    - missingness_interval: int
        Number of minutes for period in output matrix, allowing for fractional missingness. \
        Should be a whole number multiple of basis_rate.
   
    - missing_flag_col: str 
        Name of column in flagged_df with binary missingness flags. Default from flag_missing_data is 'Missing_Flag'

    - datetime_col : str
        Name of column in flagged_df with timestamps. Default from flag_missing_data is 'datetime'.
        
    - groupby_col : str
        Name of coluumn in flagged_df to group by. e.g. participant ID. 

    Returns
    -------
    - Dataframe matrix with index defined by groupby_col, and each column representing one time point.
    """

    # Check if missingness_interval > basis_rate
    if missingness_interval < basis_rate:
        raise ValueError("Resampling Error: `missingness_interval` must be greater than `basis_rate`.")
    
    # Check if missingness_interval is a multiple of basis_rate
    if missingness_interval % basis_rate != 0:
        raise ValueError("`missingness_interval` must be a whole number multiple of `basis_rate`")

    # Convert Missing_Flag to integer to calculate percentages later
    flagged_df[missing_flag_col] = flagged_df[missing_flag_col].astype(int)

    # Create matrix
    matrix = flagged_df.pivot(index=groupby_col, columns=datetime_col, values=missing_flag_col)

    # Calculate the number of basis_rate intervals within each missingness_interval
    intervals_per_group = missingness_interval // basis_rate

    # Use rolling mean to calculate the percentage of missing values within each interval
    # Note: The window size is set to intervals_per_group, and min_periods is set to 1 to ensure that we get a value even if there's only one non-missing value in the window.
    resampled_matrix = matrix.rolling(window=intervals_per_group, axis=1, min_periods=1).mean()

    # Since rolling mean includes the current and previous (window-1) columns, we need to select every intervals_per_group-th column to get non-overlapping intervals
    resampled_matrix = resampled_matrix.iloc[:, [i for i in range(0, len(resampled_matrix.columns), intervals_per_group)]]

    return resampled_matrix